In [3]:
x=[i**(i+1) for i in range(3)]


In [4]:
x

[0, 1, 8]

In [21]:
import numpy as np
x=np.arange(1,21).reshape(4,5)
y=np.arange(21,41).reshape(4,5)

In [20]:
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [25]:
np.hstack((x,y))

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35],
       [16, 17, 18, 19, 20, 36, 37, 38, 39, 40]])

In [26]:
np.vstack((x,y))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [28]:
np.dstack((y,x))

array([[[21,  1],
        [22,  2],
        [23,  3],
        [24,  4],
        [25,  5]],

       [[26,  6],
        [27,  7],
        [28,  8],
        [29,  9],
        [30, 10]],

       [[31, 11],
        [32, 12],
        [33, 13],
        [34, 14],
        [35, 15]],

       [[36, 16],
        [37, 17],
        [38, 18],
        [39, 19],
        [40, 20]]])

In [29]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [30]:
data=np.random.randn(7,4)

In [31]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [32]:
data

array([[-0.31843352,  0.72621644,  0.22917059,  0.24752317],
       [ 0.01494998,  1.17918617,  0.2107773 , -1.13591888],
       [ 1.19505837, -0.24375248,  0.48759302, -0.33390162],
       [ 0.01667627, -0.33334135, -0.37471541,  0.76665197],
       [ 0.97679167, -0.53404375,  1.109713  ,  1.422817  ],
       [-0.1530798 , -0.68722613,  0.18393157,  1.05857417],
       [ 0.06518378, -0.30707385,  0.53910539, -0.26288735]])

In [40]:
n=names==['Bob']